baseURL = "https://yieldedge.co/"
languageCode = "en-us"
title = "Digital Frontier - Tech & Finance Reviews"
theme = "placeholder"

[params]
  description = "Reviews of VPN, Crypto Casinos, Finance tools and more"
  author = "Your Name"
  email = "contact@example.com"
  site_logo = "/images/logo.png"
  
[params.social]
  twitter = "@yourhandle"
  
[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[imaging]
  resampleFilter = "lanczos"
  quality = 85
